# Generated by Django 3.1.3 on 2020-11-30 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('author', models.CharField(max_length=50)),
                ('category', models.CharField(max_length=30)),
                ('state', models.CharField(max_length=20)),
                ('observations', models.CharField(max_length=200, null=True)),
                ('image', models.ImageField(null=True, upload_to='')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Libro',
                'verbose_name_plural': 'Libros',
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('lastname', models.CharField(max_length=30)),
                ('identification', models.CharField(max_length=15, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.CharField(max_length=15, null=True)),
                ('image', models.ImageField(null=True, upload_to='')),
                ('address', models.CharField(max_length=50, null=True)),
                ('birthdate', models.DateField(null=True)),
                ('gender', models.CharField(max_length=40, null=True)),
                ('program', models.CharField(max_length=40)),
                ('semester', models.CharField(max_length=40)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Estudiante',
                'verbose_name_plural': 'Estudiantes',
            },
        ),
        migrations.CreateModel(
            name='loanHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(max_length=20)),
                ('return_date', models.DateTimeField(null=True)),
                ('observations', models.CharField(max_length=200, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now_add=True)),
                ('books', models.ManyToManyField(to='ReconocimientoFacial.Book')),
                ('students', models.ManyToManyField(to='ReconocimientoFacial.Student')),
            ],
            options={
                'verbose_name': 'Historial_prestamo',
                'verbose_name_plural': 'Historial_prestamos',
            },
        ),
    ]
